### ISSUE TITLE
Functions followed with full-width parenthesis

### ISSUE THREAD

**Issue by imba-tjd** [MicrosoftDocs/sql-docs.zh-cn#16] opened 2018-02-20 04:20 UTC
I noticed there are many functions followed with full-width parenthesis.

For example in https://docs.microsoft.com/zh-cn/sql/xquery/xquery-language-reference-sql-server:
![image](https://user-images.githubusercontent.com/24759802/36406442-c80bca58-1631-11e8-9f80-27c14936799c.png)
GitHub searcher doesn't support searching parenthesis. I cloned this repository and use regular expression to search other files.
```
Search Criteria

File name:                                                             
Containing text:  (?<=[A-z\s])+（[A-z\s]*(）|\))                         
Look in:          C:\Users\user\OneDrive\GitHub\sql-docs.zh-cn\docs\  


Search Statistics

Found:      356 items (3.61 MB)       
Text:       1,155 hits                
Searched:   17,726 items (129.23 MB)  
Checked:    18,174 items (129.23 MB)  
Status:     Completed (05 secs)       
```
My regular expression may match incorrectly and the quantity is large, so I think this issue should be managed by you team.

This exist both in `live` branch and `FromPrivateLive` branch. And **zh-tw repository also exists**.

**Comment by CeciAc** [comment] 2018-03-19 18:54
Hi all, this looks like a source issue but I cannot move it to the en-US repo on my side.
Assigning it to @carolinacmoravia to check this issue. 
@ishasahni1

**Comment by carolinacmoravia** [comment] 2018-04-09 19:51
Hello, @imba-tjd, 
Could you indicate which string you suggest to modify, please? Thanks in advance.

**Comment by imba-tjd** [comment] 2018-04-10 02:17
@carolinacmoravia 
`query （)方法` and `Query （） 方法` should be `query ()方法`.

**Comment by ishasahni1** [comment] 2018-04-10 04:35
@imba-tjd @carolinacmoravia Thank you for the valuable feedback, we have shared this feedback with the content team and have requested to make the fix on the source files as per the feedback suggested. Will keep you posted once the issue is fixed on the source.

**Comment by ishasahni1** [comment] 2018-04-11 20:09
@imba-tjd @carolinacmoravia the above feedback was taken into consideration and the issue is now resolved on the topic live on docs.microsoft.com

**Closed by ishasahni1** 2018-04-11 20:10 UTC
Labels: Source Issue
